Edit with OnlyOffice buttons are missing. #27
xwikisas/application-onlyoffice-connector pull request #28
Opened 2022-09-01 09:27 UTC by trrenty

Since XWiki 14.6, the attachments of a page are displayed using a live table, thus the script that decorated the attachments with the OnlyOffice buttons had to be modified.

Firstly, the buttons did not appear because when the listeners were triggered, the live table was not loaded fully, therefore there were no attachments to be decorated. If it did happen to be loaded, the buttons would not appear in the expected place (underneath the 'Actions' tab).

![image](https://user-images.githubusercontent.com/45433221/187880023-fd7f394c-9728-4528-abbd-f2a9acbb7870.png)

The current version looks like this:
* XWiki >= 14.6
![image](https://user-images.githubusercontent.com/45433221/187879184-fbf774fd-157c-4b8c-bd20-f577fdee6ed3.png)

* XWiki < 14.6
![image](https://user-images.githubusercontent.com/45433221/187880892-ff2f67eb-9de7-4fbc-a723-e858184e4860.png)

2022-09-01 13:51 UTC, mflorea requested changes

2022-09-01 13:51 UTC, mflorea commented on application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/UI.xml
> +  #if ($request.get('hasPagination') == 'true')
The concept of pagination doesn't make much sense here the the 'link' display type could make sense elsewhere, outside of the live table. WDYT about:

```suggestion
  #if ($request.get('asLink') == 'true')
```

or something similar. My point is that the flag should be more about the return value (link vs. button) rather than about where the return value is used (if possible).

On the other hand, note that we will replace the live table with live data very soon, see https://github.com/xwiki/xwiki-platform/pull/1888 , so it would be nice to make it work also with Live Data so that it's future proof (i.e. see if you can use the same HTML structure with live data).

2022-09-01 13:51 UTC, mflorea commented on application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/UI.xml
> +    &lt;span class="action-icon"&gt;&lt;img src="$logoURL"/&gt;&lt;/span&gt;
Missing ``alt`` attribute (also below).

2022-09-01 13:51 UTC, mflorea commented on application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/XooEdit.xml
> +      <use>onDemand</use>
:+1:

2022-09-01 13:51 UTC, mflorea commented on application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/XooEdit.xml
> +  $(document).on('xwiki:livetable:docAttachments:loadingComplete', decorateWithXooButtons);
Would be nice to make this work with live data too, see my comment above.

2022-09-01 13:52 UTC, mflorea commented on application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/UI.xml
> +  #if ($request.get('hasPagination') == 'true')
Note that you can test with live data using ``?viewer=attachments&useLiveData=true``.

2022-09-05 09:20 UTC, trrenty commented
Now also compatible with LiveData.

![image](https://user-images.githubusercontent.com/45433221/188411813-7681abf0-4881-4a3c-ba40-720847aad2d6.png)

2022-09-05 09:59 UTC, mflorea requested changes
Almost there :)

2022-09-05 09:59 UTC, mflorea commented on application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/XooEdit.xml
> +    if ($(event.target).attr('id').indexOf("docAttachments") &gt;= 0) {
Why not check for string equality? Is there a use case where the id ``docAttachments`` has a prefix / suffix?

2022-09-05 09:59 UTC, mflorea commented on application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/XooEdit.xml
> +      setTimeout(decorateWithXooButtons, 0);
I would add a comment explaining the ``setTimeout(0)`` (i.e. to allow the live data to display the entries).

2022-09-05 10:19 UTC, trrenty commented on application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/XooEdit.xml
> +    if ($(event.target).attr('id').indexOf("docAttachments") &gt;= 0) {
No. But I was thinking of the possible human error of using an id such as `id="id1 id2"` - since running `$('elementWithSpaceInID').attr('id')` will return `id1 id2`.

2022-09-05 14:20 UTC, mflorea commented on application-onlyoffice-connector-ui/src/main/resources/XWikiOnlyOfficeCode/XooEdit.xml
> +    if ($(event.target).attr('id').indexOf("docAttachments") &gt;= 0) {
That would be a bug on the code that uses ``id="id1 id2"``. I don't think you need to care about this.

2022-09-05 14:21 UTC, mflorea approved these changes

2022-09-06 12:55 UTC, merged